package com.nfm.comsol.fullcell;

import com.comsol.model.Model;
import com.comsol.model.util.ModelUtil;
import com.nfm.comsol.config.FullCellConfig;
import com.nfm.comsol.config.MaterialConfig;
import com.nfm.comsol.config.SimulationConfig;
import com.nfm.comsol.util.ValidationUtils;

/** Orchestrates the complete 3D explicit-particle representative-cell model. */
public final class FullCellModelBuilder {
    private final FullCellParameterBuilder parameters = new FullCellParameterBuilder();
    private final FullCellGeometryBuilder geometry = new FullCellGeometryBuilder();
    private final FullCellDefinitionsBuilder definitions = new FullCellDefinitionsBuilder();
    private final FullCellPhysicsBuilder physics = new FullCellPhysicsBuilder();
    private final FullCellMeshBuilder mesh = new FullCellMeshBuilder();
    private final FullCellStudyBuilder studies = new FullCellStudyBuilder();
    private final FullCellResultBuilder results = new FullCellResultBuilder();

    public BuiltFullCell build(MaterialConfig material, FullCellConfig cell, SimulationConfig simulation,
                               double cRate, boolean smokeTest,
                               boolean transitionSmokeTest,
                               SensitivityCase sensitivity) {
        Model model = ModelUtil.create("FullCellModel");
        model.label(material.name() + " 3D heterogeneous Na full-cell model");
        model.comments("Generated by Java API for COMSOL 6.4. Quantitative claims are blocked while required data remain provisional.");
        parameters.build(model, material, cell, cRate, sensitivity);
        geometry.build(model);
        definitions.build(model, material, cell);
        physics.build(model);
        mesh.build(model, simulation, cell, smokeTest);
        studies.build(model, simulation, smokeTest, transitionSmokeTest);
        results.build(model, simulation, material, cell);
        ValidationUtils.validateFullCellModel(model);
        return new BuiltFullCell(model, studies, results);
    }

    public static final class BuiltFullCell {
        private final Model model;
        private final FullCellStudyBuilder studies;
        private final FullCellResultBuilder results;

        public BuiltFullCell(Model model, FullCellStudyBuilder studies, FullCellResultBuilder results) {
            this.model = model;
            this.studies = studies;
            this.results = results;
        }

        public Model model() { return model; }
        public FullCellStudyBuilder studies() { return studies; }
        public FullCellResultBuilder results() { return results; }
    }
}
